name: "dotnet-func-ci"
description: "Builds, tests, publishes, and optionally uploads artifacts and NuGet packages for Azure Functions projects"

inputs:
  dotnet-project:
    description: "The .NET project to build and test"
    required: true
  dotnet-version:
    description: "The version(s) of .NET to use (comma or newline separated)"
    required: true
    default: "9.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  use-framework-output-root:
    description: "Set to true to upload the first target framework folder (e.g. net10.0) instead of the parent bin/Release folder"
    required: false
    default: "true"
  skip-artifact-upload:
    description: "Set to true to skip uploading the published function application artifact"
    required: false
    default: "false"
  skip-nuget-artifact-upload:
    description: "Set to true to skip uploading NuGet package artifacts"
    required: false
    default: "false"

outputs:
  build_version:
    description: "NuGet package version resolved by Nerdbank.GitVersioning"
    value: ${{ steps.nbgv-metadata.outputs.build_version }}
  semver:
    description: "SemVer2 value"
    value: ${{ steps.nbgv-metadata.outputs.semver }}
  
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Resolve Nerdbank.GitVersioning metadata
      id: nbgv-metadata
      uses: frasermolyneux/actions/nbgv-metadata@nbgv-metadata/v1
      with:
        perform-checkout: 'false'

    - name: Setup .NET SDKs
      uses: frasermolyneux/actions/dotnet-sdk-setup@dotnet-sdk-setup/v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --configuration Release --no-restore \
          /p:ContinuousIntegrationBuild=true \
          /p:IncludeSymbols=true \
          /p:SymbolPackageFormat=snupkg

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --configuration Release --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests

    - name: Set project artifact path
      shell: pwsh
      run: |
        $basePath = Join-Path "src" "${{ inputs.dotnet-project }}"
        $releasePath = Join-Path $basePath "bin/Release"
        $useFrameworkRoot = "${{ inputs.use-framework-output-root }}" -eq "true"

        if ($useFrameworkRoot) {
          if (-not (Test-Path $releasePath)) {
            throw "Release output folder not found: $releasePath. Ensure the project built successfully."
          }

          $frameworkDirs = Get-ChildItem -Path $releasePath -Directory | Where-Object { $_.Name -like 'net*' }

          if ($frameworkDirs.Count -eq 0) {
            throw "No target framework folder found under $releasePath."
          }

          if ($frameworkDirs.Count -gt 1) {
            throw "Multiple target framework folders found under $releasePath. Disable use-framework-output-root or limit to a single target framework."
          }

          $artifactPath = $frameworkDirs[0].FullName
          Write-Host "Using framework-specific artifact path: $artifactPath"
        }
        else {
          $artifactPath = $releasePath
          Write-Host "Using artifact path: $artifactPath"
        }

        "ARTIFACT_PATH=$artifactPath" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Upload artifact ${{ inputs.dotnet-project }}
      if: inputs.skip-artifact-upload != 'true'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.dotnet-project }}
        path: ${{ env.ARTIFACT_PATH }}
        if-no-files-found: error
        include-hidden-files: true

    - name: Upload NuGet Packages
      if: inputs.skip-nuget-artifact-upload != 'true'
      uses: actions/upload-artifact@v6
      with:
        name: nuget-packages
        path: |
          **/bin/Release/**/*.nupkg
          **/bin/Release/**/*.snupkg