name: "deploy-function-app"

inputs:
  function-app-artifact-name:
    description: "The name of the function app artifact to deploy"
    required: true
  function-app-name:
    description: "The name of the function app to deploy"
    required: true
  function-app-resource-group:
    description: "The resource group containing the function app"
    required: true
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: 'Az CLI Login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.function-app-artifact-name }}
        path: artifacts/${{ inputs.function-app-artifact-name }}

    - name: Prepare deployment package
      shell: pwsh
      run: |
        $artifactRoot = Join-Path "artifacts" "${{ inputs.function-app-artifact-name }}"
        if (-not (Test-Path $artifactRoot)) {
          Write-Error "Artifact path not found: $artifactRoot"
          exit 1
        }

        $existingZip = Get-ChildItem -Path $artifactRoot -Filter *.zip -File -Recurse | Select-Object -First 1
        if ($existingZip) {
          $zipPath = $existingZip.FullName
        }
        else {
          $zipPath = Join-Path $env:RUNNER_TEMP "functionapp.zip"
          if (Test-Path $zipPath) {
            Remove-Item $zipPath -Force
          }
          Compress-Archive -Path (Join-Path $artifactRoot '*') -DestinationPath $zipPath
        }

        "FUNCTIONAPP_ZIP_PATH=$zipPath" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Deploy to Azure Function App
      shell: bash
      run: |
        set -euo pipefail
        az functionapp deployment source config-zip \
          --resource-group "${{ inputs.function-app-resource-group }}" \
          --name "${{ inputs.function-app-name }}" \
          --src "$FUNCTIONAPP_ZIP_PATH"