name: "logic-app-ci"

inputs:
  logic-project:
    description: "The name of the logic app (same as the folder name)"
    required: true
  src-folder:
    description: "The folder containing the projects"
    required: true
    default: "src"
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Upload artifact ${{ inputs.logic-project }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.logic-project }}
        path: "src/${{ inputs.logic-project }}"
        if-no-files-found: error
        include-hidden-files: true
