name: "dotnet-ci"

inputs:
  dotnet-version:
    description: "The version(s) of .NET to use (comma or newline separated)"
    required: true
    default: "9.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  
runs:
  using: "composite"
  steps:
    - name: Resolve Nerdbank.GitVersioning metadata
      shell: pwsh
      run: |
        dotnet tool update --global nbgv
        $toolPath = Join-Path $HOME '.dotnet/tools'
        if (Test-Path $toolPath) {
          $Env:PATH = "$toolPath${[System.IO.Path]::PathSeparator}$Env:PATH"
          Add-Content -Path $Env:GITHUB_PATH -Value $toolPath
        }

        try {
          nbgv cloud
          $versionInfo = nbgv get-version -f json | ConvertFrom-Json
        }
        catch {
          throw 'Failed to read Nerdbank.GitVersioning metadata. Ensure version.json exists in the repository.'
        }

        if (-not $versionInfo) {
          throw 'Nerdbank.GitVersioning did not return version information.'
        }

        Write-Host "SemVer: $($versionInfo.SemVer2)"
        Write-Host "NuGet version: $($versionInfo.NuGetPackageVersion)"
        Write-Host "Assembly version: $($versionInfo.AssemblyVersion)"
        Write-Host "File version: $($versionInfo.AssemblyFileVersion)"

        "BUILD_VERSION=$($versionInfo.NuGetPackageVersion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "SEMVER=$($versionInfo.SemVer2)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "ASSEMBLY_VERSION=$($versionInfo.AssemblyVersion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "FILE_VERSION=$($versionInfo.AssemblyFileVersion)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        "PUBLIC_RELEASE=$($versionInfo.PublicRelease)" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Resolve .NET SDK versions
      id: dotnet_versions
      shell: pwsh
      run: |
        $raw = "${{ inputs.dotnet-version }}"
        $entries = $raw -split "`r?`n" | ForEach-Object { $_.Trim() } | Where-Object { $_ }
        if (-not $entries) {
          throw 'No dotnet versions provided. Specify at least one value in dotnet-version input.'
        }

        $stable = @()
        $preview = @()
        foreach ($entry in $entries) {
          if ($entry -match '^(?<base>.+?)-preview.*$') {
            $preview += $matches['base']
          }
          else {
            $stable += $entry
          }
        }

        if (-not $stable -and -not $preview) {
          throw 'Unable to resolve any dotnet versions from provided input.'
        }

        if ($stable) {
          Write-Host 'Stable .NET SDK versions:'
          $stable | ForEach-Object { Write-Host " - $_" }
          $marker = 'EOF'
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "stable_versions<<$marker"
          Add-Content -Path $Env:GITHUB_OUTPUT -Value ($stable -join "`n")
          Add-Content -Path $Env:GITHUB_OUTPUT -Value $marker
        }

        if ($preview) {
          Write-Host 'Preview .NET SDK versions:'
          $preview | ForEach-Object { Write-Host " - $_ (preview quality)" }
          $marker = 'EOF'
          Add-Content -Path $Env:GITHUB_OUTPUT -Value "preview_versions<<$marker"
          Add-Content -Path $Env:GITHUB_OUTPUT -Value ($preview -join "`n")
          Add-Content -Path $Env:GITHUB_OUTPUT -Value $marker
        }
      
    - name: Setup .NET (stable)
      if: steps.dotnet_versions.outputs.stable_versions != ''
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.dotnet_versions.outputs.stable_versions }}

    - name: Setup .NET (preview)
      if: steps.dotnet_versions.outputs.preview_versions != ''
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ steps.dotnet_versions.outputs.preview_versions }}
        dotnet-quality: 'preview'

    - name: Setup Package Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --configuration Release --no-restore
      
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --configuration Release --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests

    - name: Upload NuGet Packages
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: '**/bin/Release/**/*.nupkg'