name: "nbgv-metadata"

description: "Resolve Nerdbank.GitVersioning metadata and expose the computed values"

inputs:
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - id: nbgv
      name: Resolve Nerdbank.GitVersioning metadata
      shell: pwsh
      run: |
        $toolPath = Join-Path $PWD '.nbgv-tool'
        if (Test-Path $toolPath) {
          Remove-Item -Path $toolPath -Recurse -Force
        }

        dotnet tool install --tool-path $toolPath nbgv
        $nbgvExe = if ($IsWindows) { Join-Path $toolPath 'nbgv.exe' } else { Join-Path $toolPath 'nbgv' }
        $Env:PATH = "$toolPath${[System.IO.Path]::PathSeparator}$Env:PATH"
        Add-Content -Path $Env:GITHUB_PATH -Value $toolPath

        try {
          & $nbgvExe cloud
          $versionInfo = & $nbgvExe get-version -f json | ConvertFrom-Json
        }
        catch {
          throw 'Failed to read Nerdbank.GitVersioning metadata. Ensure version.json exists in the repository.'
        }

        if (-not $versionInfo) {
          throw 'Nerdbank.GitVersioning did not return version information.'
        }

        Write-Host "SemVer: $($versionInfo.SemVer2)"
        Write-Host "NuGet version: $($versionInfo.NuGetPackageVersion)"
        Write-Host "Assembly version: $($versionInfo.AssemblyVersion)"
        Write-Host "File version: $($versionInfo.AssemblyFileVersion)"

        $envMap = @{
          BUILD_VERSION   = $versionInfo.NuGetPackageVersion
          SEMVER          = $versionInfo.SemVer2
          ASSEMBLY_VERSION = $versionInfo.AssemblyVersion
          FILE_VERSION     = $versionInfo.AssemblyFileVersion
          PUBLIC_RELEASE   = $versionInfo.PublicRelease
        }

        foreach ($pair in $envMap.GetEnumerator()) {
          "{0}={1}" -f $pair.Key, $pair.Value | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        }

        $outputMap = @{
          build_version   = $versionInfo.NuGetPackageVersion
          semver          = $versionInfo.SemVer2
          assembly_version = $versionInfo.AssemblyVersion
          file_version     = $versionInfo.AssemblyFileVersion
          public_release   = $versionInfo.PublicRelease
        }

        foreach ($pair in $outputMap.GetEnumerator()) {
          "{0}={1}" -f $pair.Key, $pair.Value | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
        }

outputs:
  build_version:
    description: "NuGet package version resolved by Nerdbank.GitVersioning"
    value: ${{ steps.nbgv.outputs.build_version }}
  semver:
    description: "SemVer2 value"
    value: ${{ steps.nbgv.outputs.semver }}
  assembly_version:
    description: "Assembly version"
    value: ${{ steps.nbgv.outputs.assembly_version }}
  file_version:
    description: "Assembly file version"
    value: ${{ steps.nbgv.outputs.file_version }}
  public_release:
    description: "Indicates whether the commit is considered a public release"
    value: ${{ steps.nbgv.outputs.public_release }}
