name: "dotnet-sql-ci"

inputs:
  project-folder:
    description: "The folder containing the SQL Project"
    required: true
    default: "src/database"
  project-file:
    description: "The SQL Project file"
    required: true
    default: "database.sqlproj"
  
runs:
  using: "composite"
  steps:
    - uses: azure/sql-action@v2
      with:        
        path: '${{ inputs.project-folder }}/${{ inputs.project-file }}'
        action: 'publish'
        build-arguments: '-c Release'                 
