name: "dotnet-sql-ci"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "7.0.x"
  src-folder:
    description: "The folder containing the SQL Project"
    required: true
    default: "src/database"
  
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --no-restore --configuration Release
      
    - name: Upload artifact database
      uses: actions/upload-artifact@v3
      with:
        name: database
        path: ${{ inputs.src-folder }}/bin/Release/database.dacpac
