name: "deploy-logic-app"

inputs:
  logic-app-artifact-name:
    description: "The name of the logic app artifact to deploy"
    required: true
  logic-app-name:
    description: "The name of the logic app to deploy"
    required: true
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: 'Az CLI Login'
      uses: azure/login@v1
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.logic-app-artifact-name }}
        path: artifacts/${{ inputs.logic-app-artifact-name }}

    - name: Deploy to Azure Logic App
      id: deploy-to-webapp
      uses: azure/functions-action@v1
      with:
        app-name: ${{ inputs.logic-app-name }}
        package: artifacts/${{ inputs.logic-app-artifact-name }}