name: "deploy-sql-database"

inputs:
  sql-args:
    description: "Sql args that can contain environment variable se.g. /Variables:env=dev /Variables:instance=01"
    required: true
  sql-server-fqdn:
    description: "The SQL Server fully qualified domain name"
    required: true
  sql-database-name:
    description: "The target SQL Database name"
    required: true
  project-folder:
    description: "The folder containing the SQL Project"
    required: true
    default: "src/database"
  project-file:
    description: "The SQL Project file"
    required: true
    default: "database.sqlproj"
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: 'Az CLI Login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.AZURE_CLIENT_ID }}
        tenant-id: ${{ inputs.AZURE_TENANT_ID }}
        subscription-id: ${{ inputs.AZURE_SUBSCRIPTION_ID }}

    - name: 'Install dotnet tools'
      shell: bash
      run: dotnet tool install -g microsoft.sqlpackage

    - uses: azure/sql-action@v2.3
      with:  
        connection-string: 'Server=tcp:${{ inputs.sql-server-fqdn }};Authentication=Active Directory Default; Database=${{ inputs.sql-database-name }};'   
        path: '${{ inputs.project-folder }}/${{ inputs.project-file }}'
        action: 'publish'
        build-arguments: '-c Release'
        arguments: '${{ inputs.sql-args }}'        
