name: "terraform-plan-and-apply"
description: "Runs terraform plan and apply in a single job with Azure OIDC authentication, optionally posting plan results to the PR"

inputs:
  terraform-folder:
    description: "The folder containing the Terraform projects"
    required: true
    default: "terraform"
    type: string
  terraform-var-file:
    description: "The var-file to to be used for the Terraform plan (tfvars/dev.tfvars, tfvars/test.tfvars, tfvars/prod.tfvars, etc.)"
    required: true
    default: "tfvars/dev.tfvars"
    type: string
  terraform-backend-file:
    description: "The backend-file to to be used for the Terraform plan (backends/dev.backend.hcl, backends/test.backend.hcl, backends/prod.backend.hcl, etc.)"
    required: false
    type: string
  terraform-additional-args:
    description: "Additional arguments to be passed to the Terraform"
    required: false
    default: ""
    type: string
  backend-subscription-id:
    description: "The backend subscription_id if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-resource-group-name:
    description: "The backend resource_group_name if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-storage-account-name:
    description: "The backend storage_account_name if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-container-name:
    description: "The backend container_name if the terraform-backend-file is not being used"
    required: false
    default: ""
    type: string
  backend-key:
    description: "The backend key if the terraform-backend-file is not being used"
    required: false
    default: ""
    type: string
  backend-tags:
    description: "The backend tags to be applied to the storage account"
    required: false
    type: string
    default: ""
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string
  plan-file-name:
    description: "Filename to write the terraform plan output (-out) and later apply"
    required: false
    default: "plan.tfplan"
    type: string
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  enable-pr-comment:
    description: "Post Terraform plan results to the pull request using terraform-pr-commenter"
    required: false
    default: "true"
    type: string
  pr-comment-workspace:
    description: "Optional TF_WORKSPACE to disambiguate PR comments in matrix runs"
    required: false
    default: ""
    type: string
  pr-comment-expand-summary-details:
    description: "Whether to expand summary details in the PR comment (EXPAND_SUMMARY_DETAILS)"
    required: false
    default: "true"
    type: string
  pr-comment-highlight-changes:
    description: "Whether to highlight plan changes in the PR comment (HIGHLIGHT_CHANGES)"
    required: false
    default: "true"
    type: string

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: true

    - name: Terraform Init
      shell: pwsh
      run: |
        cd ${{ inputs.terraform-folder }}

        $params = @("init")

        if ("${{ inputs.terraform-backend-file }}" -ne "") {
          $params += "-backend-config=${{ inputs.terraform-backend-file }}"
        }

        if ("${{ inputs.backend-subscription-id }}" -ne "") {
          $params += "-backend-config=subscription_id=${{ inputs.backend-subscription-id }}"
        }

        if ("${{ inputs.backend-resource-group-name }}" -ne "") {
          $params += "-backend-config=resource_group_name=${{ inputs.backend-resource-group-name }}"
        }

        if ("${{ inputs.backend-storage-account-name }}" -ne "") {
          $params += "-backend-config=storage_account_name=${{ inputs.backend-storage-account-name }}"
        }

        if ("${{ inputs.backend-container-name }}" -ne "") {
          $params += "-backend-config=container_name=${{ inputs.backend-container-name }}"
        }

        if ("${{ inputs.backend-key }}" -ne "") {
          $params += "-backend-config=key=${{ inputs.backend-key }}"
        }

        if ("${{ inputs.backend-tags }}" -ne "") {
          $params += "-backend-config=tags=${{ inputs.backend-tags }}"
        }

        $params += "-var-file=${{ inputs.terraform-var-file }}"

        terraform $params
      env:
        ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

    - name: Terraform Validate
      shell: bash
      run: |
        cd ${{ inputs.terraform-folder }}
        terraform validate

    - name: Terraform Plan
      id: plan
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ inputs.terraform-folder }}
        terraform plan -var-file=${{ inputs.terraform-var-file }} -out="${{ inputs.plan-file-name }}" ${{ inputs.terraform-additional-args }}
        # Show the plan in human readable form
        terraform show "${{ inputs.plan-file-name }}"
      env:
        ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

    - name: Post Terraform PR comment
      if: inputs.enable-pr-comment == 'true' && github.event_name == 'pull_request' && always() && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      uses: actions/github-script@v7
      env:
        PLAN_STDOUT: ${{ steps.plan.outputs.stdout }}
        PLAN_STDERR: ${{ steps.plan.outputs.stderr }}
        PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
        PLAN_OUTCOME: ${{ steps.plan.outcome }}
        TF_WORKSPACE: ${{ inputs.pr-comment-workspace }}
        TF_VAR_FILE: ${{ inputs.terraform-var-file }}
      with:
        script: |
          const fmt = require('${{ github.action_path }}/../terraform-pr-comment/format.js');
          const workspace = process.env.TF_WORKSPACE || '';
          const environment = fmt.deriveEnvironment(process.env.TF_VAR_FILE);
          const envSuffix = environment ? ` ${environment}` : '';
          const wsSuffix = workspace ? ` (${workspace})` : '';
          const marker = `<!-- terraform-pr-comment: plan-and-apply${envSuffix}${wsSuffix} -->`;

          const body = fmt.buildComment({
            marker,
            title: 'ðŸ—ï¸ Terraform Plan & Apply',
            workspace,
            environment,
            plan: {
              stdout: process.env.PLAN_STDOUT,
              stderr: process.env.PLAN_STDERR,
              exitcode: process.env.PLAN_EXITCODE,
              outcome: process.env.PLAN_OUTCOME,
            },
          });

          await fmt.postComment(github, context, marker, body);

    - name: Terraform Apply
      if: steps.plan.outputs.exitcode == '0'
      shell: bash
      run: |
        cd ${{ inputs.terraform-folder }}
        if [ ! -f "${{ inputs.plan-file-name }}" ]; then
          echo "Expected plan file '${{ inputs.plan-file-name }}' not found" >&2
          ls -al
          exit 1
        fi
        terraform apply -auto-approve ${{ inputs.terraform-additional-args }} "${{ inputs.plan-file-name }}"
      env:
        ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

    - name: Fail if plan failed
      if: steps.plan.outputs.exitcode != '0'
      shell: bash
      run: |
        echo "Terraform plan exit code: ${{ steps.plan.outputs.exitcode }}"
        exit 1