name: "terraform-plan-readonly"
description: "Runs terraform init, validate, and plan with Azure OIDC authentication for read-only verification, uploading the plan artifact and optionally posting results to the PR"

inputs:
  terraform-folder:
    description: "The folder containing the Terraform projects"
    required: true
    default: "terraform"
    type: string
  terraform-var-file:
    description: "The var-file to to be used for the Terraform plan (tfvars/dev.tfvars, tfvars/test.tfvars, tfvars/prod.tfvars, etc.)"
    required: true
    default: "tfvars/dev.tfvars"
    type: string
  terraform-backend-file:
    description: "The backend-file to to be used for the Terraform plan (backends/dev.backend.hcl, backends/test.backend.hcl, backends/prod.backend.hcl, etc.)"
    required: false
    default: ""
    type: string
  terraform-additional-args:
    description: "Additional arguments to be passed to the Terraform"
    required: false
    default: ""
    type: string
  backend-subscription-id:
    description: "The backend subscription_id if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-resource-group-name:
    description: "The backend resource_group_name if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-storage-account-name:
    description: "The backend storage_account_name if the terraform-backend-file is not being used"
    required: false
    type: string
  backend-container-name:
    description: "The backend container_name if the terraform-backend-file is not being used"
    required: false
    default: "tfstate"
    type: string
  backend-key:
    description: "The backend key if the terraform-backend-file is not being used"
    required: false
    default: "terraform.tfstate"
    type: string
  backend-tags:
    description: "The backend tags to be applied to the storage account"
    required: false
    type: string
    default: ""
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string
  plan-file-name:
    description: "Filename to write the terraform plan output (-out). Saved in the terraform folder."
    required: false
    default: "plan.tfplan"
    type: string
  plan-artifact-name:
    description: "The GitHub Actions artifact name to upload the plan file as."
    required: false
    default: "terraform-plan"
    type: string
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  enable-pr-comment:
    description: "Post Terraform validation/plan results to the pull request using terraform-pr-commenter"
    required: false
    default: "true"
    type: string
  pr-comment-workspace:
    description: "Optional TF_WORKSPACE to disambiguate PR comments in matrix runs"
    required: false
    default: ""
    type: string
  pr-comment-expand-summary-details:
    description: "Whether to expand summary details in the PR comment (EXPAND_SUMMARY_DETAILS)"
    required: false
    default: "true"
    type: string
  pr-comment-highlight-changes:
    description: "Whether to highlight plan changes in the PR comment (HIGHLIGHT_CHANGES)"
    required: false
    default: "true"
    type: string

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: true

    - name: Terraform Init
      shell: pwsh
      run: |
        cd ${{ inputs.terraform-folder }}

        $params = @("init")

        if ("${{ inputs.terraform-backend-file }}" -ne "") {
          $params += "-backend-config=${{ inputs.terraform-backend-file }}"
        }

        if ("${{ inputs.backend-subscription-id }}" -ne "") {
          $params += "-backend-config=subscription_id=${{ inputs.backend-subscription-id }}"
        }

        if ("${{ inputs.backend-resource-group-name }}" -ne "") {
          $params += "-backend-config=resource_group_name=${{ inputs.backend-resource-group-name }}"
        }

        if ("${{ inputs.backend-storage-account-name }}" -ne "") {
          $params += "-backend-config=storage_account_name=${{ inputs.backend-storage-account-name }}"
        }

        if ("${{ inputs.backend-container-name }}" -ne "") {
          $params += "-backend-config=container_name=${{ inputs.backend-container-name }}"
        }

        if ("${{ inputs.backend-key }}" -ne "") {
          $params += "-backend-config=key=${{ inputs.backend-key }}"
        }

        if ("${{ inputs.backend-tags }}" -ne "") {
          $params += "-backend-config=tags=${{ inputs.backend-tags }}"
        }

        $params += "-var-file=${{ inputs.terraform-var-file }}"

        terraform $params
      env:
        ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

    - name: Terraform Validate
      id: validate
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ inputs.terraform-folder }}
        terraform validate

    - name: Terraform Plan
      id: plan
      if: steps.validate.outputs.exitcode == '0'
      continue-on-error: true
      shell: bash
      run: |
        set -euo pipefail
        cd ${{ inputs.terraform-folder }}
        terraform plan -var-file=${{ inputs.terraform-var-file }} -out="${{ inputs.plan-file-name }}" ${{ inputs.terraform-additional-args }}
        # Show the plan (human readable)
        terraform show "${{ inputs.plan-file-name }}"
      env:
        ARM_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true

    - name: Post Terraform PR comment
      if: inputs.enable-pr-comment == 'true' && github.event_name == 'pull_request' && always() && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure' || steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      uses: actions/github-script@v7
      env:
        VALIDATE_STDOUT: ${{ steps.validate.outputs.stdout }}
        VALIDATE_STDERR: ${{ steps.validate.outputs.stderr }}
        VALIDATE_EXITCODE: ${{ steps.validate.outputs.exitcode }}
        VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
        PLAN_STDOUT: ${{ steps.plan.outputs.stdout }}
        PLAN_STDERR: ${{ steps.plan.outputs.stderr }}
        PLAN_EXITCODE: ${{ steps.plan.outputs.exitcode }}
        PLAN_OUTCOME: ${{ steps.plan.outcome }}
        TF_WORKSPACE: ${{ inputs.pr-comment-workspace }}
      with:
        script: |
          const workspace = process.env.TF_WORKSPACE ? ` (${process.env.TF_WORKSPACE})` : '';
          const marker = `<!-- terraform-pr-comment: plan${workspace} -->`;

          let body = marker + '\n';
          body += `### Terraform Results${workspace}\n\n`;

          // Validate section
          const validateOutcome = process.env.VALIDATE_OUTCOME;
          if (validateOutcome === 'success' || validateOutcome === 'failure') {
            const validateIcon = process.env.VALIDATE_EXITCODE === '0' ? '✅' : '❌';
            const validateOutput = (process.env.VALIDATE_STDOUT || '') + (process.env.VALIDATE_STDERR || '');
            body += `#### ${validateIcon} Validate\n\n`;
            if (validateOutput.trim()) {
              body += `<details><summary>Output</summary>\n\n\`\`\`\n${validateOutput.trim()}\n\`\`\`\n\n</details>\n\n`;
            }
          }

          // Plan section
          const planOutcome = process.env.PLAN_OUTCOME;
          if (planOutcome === 'success' || planOutcome === 'failure') {
            const planIcon = process.env.PLAN_EXITCODE === '0' ? '✅' : '❌';
            const planOutput = (process.env.PLAN_STDOUT || '') + (process.env.PLAN_STDERR || '');
            body += `#### ${planIcon} Plan\n\n`;
            if (planOutput.trim()) {
              let trimmed = planOutput.trim();
              if (trimmed.length > 60000) {
                trimmed = trimmed.substring(trimmed.length - 60000);
                trimmed = '... (truncated)\n' + trimmed;
              }
              body += `<details><summary>Output</summary>\n\n\`\`\`hcl\n${trimmed}\n\`\`\`\n\n</details>\n\n`;
            }
          }

          // Find and update existing comment or create new one
          const { data: comments } = await github.rest.issues.listComments({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            per_page: 100,
          });

          const existing = comments.find(c => c.body && c.body.includes(marker));
          if (existing) {
            await github.rest.issues.updateComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: existing.id,
              body,
            });
          } else {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body,
            });
          }

    - name: Upload Terraform Plan Artifact
      if: steps.plan.outputs.exitcode == '0'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.plan-artifact-name }}
        path: ${{ inputs.terraform-folder }}/${{ inputs.plan-file-name }}
        if-no-files-found: error

    - name: Fail if validate or plan failed
      if: steps.validate.outputs.exitcode != '0' || steps.plan.outputs.exitcode != '0'
      shell: bash
      run: |
        echo "Terraform validate exit code: ${{ steps.validate.outputs.exitcode }}"
        echo "Terraform plan exit code: ${{ steps.plan.outputs.exitcode }}"
        exit 1
