name: "run-api-integration-tests"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "8.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  api-base-url:
    description: "The base URL of the API to test"
    required: true
  api-key:
    description: "The test account API key"
    required: true
  api-audience:
    description: "The API audience"
    required: true
  AZURE_CLIENT_ID:
    description: "The test account client id"
    required: true
  AZURE_CLIENT_SECRET:
    description: "The test account client secret"
    required: true
  AZURE_TENANT_ID:
    description: "The test account tenant id"
    required: true

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --no-restore

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --no-build --verbosity normal --filter FullyQualifiedName~IntegrationTests
      env:
        api_base_url: ${{ inputs.api-base-url }}
        api_key: ${{ inputs.api-key }}
        api_audience: ${{ inputs.api-audience }}
        AZURE_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ inputs.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}