name: "run-api-integration-tests"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "7.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  api-base-url:
    description: "The base URL of the API to test"
    required: true
  AZURE_CLIENT_ID: 
    description: "The azure client/application ID configured for federated access"
    required: true
    type: string
  AZURE_TENANT_ID: 
    description: "The target Azure tenant"
    required: true
    type: string
  AZURE_SUBSCRIPTION_ID: 
    description: "The target Azure subscription"
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --no-restore
      
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --no-build --verbosity normal --filter FullyQualifiedName~IntegrationTests
      env:
        api_base_url: ${{ inputs.api-base-url}}