name: "run-api-integration-tests"
description: "Runs .NET API integration tests with Azure OIDC authentication"

inputs:
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "9.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  api-base-url:
    description: "The base URL of the API to test"
    required: true
  api-key:
    description: "The test account API key"
    required: true
  api-audience:
    description: "The API audience"
    required: true
  AZURE_CLIENT_ID:
    description: "The test account client id"
    required: true
  AZURE_CLIENT_SECRET:
    description: "The test account client secret"
    required: true
  AZURE_TENANT_ID:
    description: "The test account tenant id"
    required: true
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --no-restore

    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --no-build --verbosity normal --filter FullyQualifiedName~IntegrationTests
      env:
        api_base_url: ${{ inputs.api-base-url }}
        api_key: ${{ inputs.api-key }}
        api_audience: ${{ inputs.api-audience }}
        AZURE_CLIENT_ID: ${{ inputs.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ inputs.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ inputs.AZURE_TENANT_ID }}