name: "publish-nuget-packages"

inputs:
  artifact-name:
    description: "The name of the artifact that contains the packages"
    required: true
  NUGET_API_KEY: 
    description: "The NuGet API key"
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}

    - uses: nuget/setup-nuget@v2
      with:
        nuget-version: '5.x'

    - name: Publish to NuGet.org
      shell: bash
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ inputs.NUGET_API_KEY }}