name: "publish-nuget-packages"
description: "Publish NuGet packages and symbols, skipping symbol push when nupkg uploads are duplicates"

inputs:
  artifact-name:
    description: "The name of the artifact that contains the packages"
    required: true
  artifact-run-id:
    description: "Optional workflow run id to download artifacts from"
    required: false
    default: ""
  github-token:
    description: "Token required when downloading artifacts from another workflow run"
    required: false
    default: ""
  artifact-output-path:
    description: "Directory to download and publish artifact contents"
    required: false
    default: "."
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"

runs:
  using: "composite"

  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Download artifact from build job (current run)
      if: inputs.artifact-run-id == ''
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-output-path }}

    - name: Download artifact from specified run
      if: inputs.artifact-run-id != ''
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-output-path }}
        run-id: ${{ inputs.artifact-run-id }}
        github-token: ${{ inputs.github-token }}

    - name: Publish to NuGet.org
      shell: bash
      run: |
        set -euo pipefail
        cd "${{ inputs.artifact-output-path }}"

        NUGET_LOG=/tmp/nuget-push.log
        dotnet nuget push "**/*.nupkg" --source 'https://api.nuget.org/v3/index.json' --api-key "$NUGET_API_KEY" --skip-duplicate | tee "$NUGET_LOG"

        if grep -q "Successfully published" "$NUGET_LOG"; then
          PUBLISH_SYMBOLS=true
          echo "nupkg publish succeeded; proceeding to symbols"
        else
          PUBLISH_SYMBOLS=false
          echo "nupkg publish skipped (likely duplicates); skipping symbol publish"
        fi

        if [[ "$PUBLISH_SYMBOLS" == "true" ]]; then
          if find . -type f -name '*.snupkg' | grep -q .; then
            dotnet nuget push "**/*.snupkg" --source 'https://api.nuget.org/v3/index.json' --api-key "$NUGET_API_KEY" --skip-duplicate
          else
            echo 'No symbol packages detected; skipping symbol publish.'
          fi
        fi