name: "dotnet-web-ci"

inputs:
  dotnet-project:
    description: "The .NET project to build and test"
    required: true
  dotnet-version:
    description: "The version of .NET to use"
    required: true
    default: "7.0.x"
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  
runs:
  using: "composite"
  steps:
    - name: Get Build Version
      shell: pwsh
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build -p:Version=$BUILD_VERSION --no-restore
      
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests

    - name: dotnet publish ${{ inputs.dotnet-project }}
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet publish ${{ inputs.dotnet-project }}/${{ inputs.dotnet-project }}.csproj --configuration Release --output ${{env.DOTNET_ROOT}}/${{ inputs.dotnet-project }}

    - name: Upload artifact ${{ inputs.dotnet-project }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.dotnet-project }}
        path: ${{env.DOTNET_ROOT}}/${{ inputs.dotnet-project }}