name: "dotnet-web-ci"
description: "Builds, tests, publishes, and optionally uploads artifacts and NuGet packages for ASP.NET Core web projects"

inputs:
  dotnet-project:
    description: "The .NET project to build and test"
    required: true
  dotnet-version:
    description: "The version(s) of .NET to use (comma or newline separated)"
    required: true
    default: "9.0.x"
  publish-frameworks:
    description: "Optional list (comma or newline separated) of target frameworks to publish explicitly"
    required: false
    default: ""
  src-folder:
    description: "The folder containing the .NET projects"
    required: true
    default: "src"
  nugetArtifactName:
    description: "The artifact name for the nuget files"
    required: true
    default: "nuget-packages"
  perform-checkout:
    description: "Set to false if the repository has already been checked out with fetch-depth 0"
    required: false
    default: "true"
  skip-artifact-upload:
    description: "Set to true to skip uploading the published web application artifact"
    required: false
    default: "false"
  skip-nuget-artifact-upload:
    description: "Set to true to skip uploading NuGet package artifacts"
    required: false
    default: "false"

outputs:
  build_version:
    description: "NuGet package version resolved by Nerdbank.GitVersioning"
    value: ${{ steps.nbgv-metadata.outputs.build_version }}
  semver:
    description: "SemVer2 value"
    value: ${{ steps.nbgv-metadata.outputs.semver }}
  
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      if: inputs.perform-checkout == 'true'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Resolve Nerdbank.GitVersioning metadata
      id: nbgv-metadata
      uses: frasermolyneux/actions/nbgv-metadata@nbgv-metadata/v1
      with:
        perform-checkout: 'false'

    - name: Resolve publish frameworks
      shell: pwsh
      run: |
        $raw = "${{ inputs.publish-frameworks }}"
        $frameworks = $raw -split '[,\s]+' | Where-Object { $_ }
        if (-not $frameworks) {
          Write-Host 'No explicit publish frameworks supplied.'
          return
        }
        $formatted = $frameworks -join "`n"
        Write-Host 'Publishing frameworks:'
        $frameworks | ForEach-Object { Write-Host " - $_" }
        $marker = '__PUBLISH_FRAMEWORKS__'
        Add-Content -Path $Env:GITHUB_ENV -Value "DOTNET_PUBLISH_FRAMEWORKS<<$marker"
        Add-Content -Path $Env:GITHUB_ENV -Value $formatted
        Add-Content -Path $Env:GITHUB_ENV -Value $marker

    - name: Setup .NET SDKs
      uses: frasermolyneux/actions/dotnet-sdk-setup@dotnet-sdk-setup/v1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Setup Package Cache
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
        
    - name: Restore Dependencies
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet restore
      
    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet build --configuration Release --no-restore \
          /p:ContinuousIntegrationBuild=true \
          /p:IncludeSymbols=true \
          /p:SymbolPackageFormat=snupkg
      
    - name: Test
      shell: bash
      run: |
        cd ${{ inputs.src-folder }}
        dotnet test --configuration Release --no-build --verbosity normal --filter FullyQualifiedName!~IntegrationTests --logger "trx;LogFileName=test-results.trx" --results-directory ./TestResults

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: test-results
        path: ${{ inputs.src-folder }}/TestResults/**/*.trx
        retention-days: 7

    - name: dotnet publish ${{ inputs.dotnet-project }}
      shell: bash
      env:
        DOTNET_PUBLISH_FRAMEWORKS: ${{ env.DOTNET_PUBLISH_FRAMEWORKS }}
      run: |
        cd ${{ inputs.src-folder }}
        publish_dir="$RUNNER_TEMP/dotnet-publish/${{ inputs.dotnet-project }}"
        rm -rf "$publish_dir"
        mkdir -p "$publish_dir"
        if [ -n "$DOTNET_PUBLISH_FRAMEWORKS" ]; then
          while IFS= read -r framework; do
            if [ -z "$framework" ]; then
              continue
            fi
            target_dir="$publish_dir/$framework"
            mkdir -p "$target_dir"
            dotnet publish ${{ inputs.dotnet-project }}/${{ inputs.dotnet-project }}.csproj --configuration Release --framework "$framework" --output "$target_dir"
          done <<< "$DOTNET_PUBLISH_FRAMEWORKS"
        else
          dotnet publish ${{ inputs.dotnet-project }}/${{ inputs.dotnet-project }}.csproj --configuration Release --output "$publish_dir"
        fi

    - name: Upload artifact ${{ inputs.dotnet-project }}
      if: inputs.skip-artifact-upload != 'true'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.dotnet-project }}
        path: ${{ runner.temp }}/dotnet-publish/${{ inputs.dotnet-project }}
        if-no-files-found: error
        include-hidden-files: true

    - name: Upload NuGet Packages
      if: inputs.skip-nuget-artifact-upload != 'true'
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.nugetArtifactName }}
        path: |
          **/bin/Release/**/*.nupkg
          **/bin/Release/**/*.snupkg